import { Feature } from 'ol';
import Map from 'ol/Map';
import { Cluster, Vector } from 'ol/source';
import { Vector as VectorLayer } from 'ol/layer';
import { Geometry } from 'ol/geom';
import VectorSource from "ol/source/Vector.js";
import SelectCreateInformationBoxController from '../notification/select-create-information-box';
import { Store } from '../../composable/store';
import IOption from '../../utils/options';
import { Render } from '../../utils/render';
import IStates from '../../utils/states';
export default class SingleSelect {
    control: SelectCreateInformationBoxController;
    private store;
    vectorSource: VectorSource;
    states: IStates;
    renderUtils: Render;
    options: IOption;
    map: Map;
    vectorLayer: VectorLayer<Vector<Geometry>>;
    constructor(renderUtils: Render, states: IStates, store: Store);
    renderCurrentSelection(states: IStates): void;
    removeCurrentSelection(): void;
    setChangeResolution(map: Map, clusterSource: Cluster, options: IOption): void;
    displayDataOnMap(map: Map, vectorLayer: VectorLayer<Vector<Geometry>>, options: IOption, vectorSource: VectorSource): void;
    setCurrentElement(feature: Feature): void;
    setIconToDisplay(feature: Feature, state: any): void;
    removeSelectedItem(feature: Feature): void;
    removeItem(feature: Feature): void;
    setInformationBox(feature: Feature): void;
    toogleDataSelection(vectorLayer: VectorLayer<Vector<Geometry>>): void;
}
