import { Feature, Map } from 'ol';
import Geolocation from 'ol/Geolocation';
import { Geometry } from 'ol/geom';
import VectorLayer from 'ol/layer/Vector';
import { Vector } from 'ol/source';
import IOption from '../utils/options';
declare function setTheme(newVal: string): void;
declare function getTheme(): string;
declare function setCustomDisplay(newVal: boolean): void;
declare function isCustomDisplay(): boolean;
declare function setTargetBoxSize(newVal: string): void;
declare function getTargetBoxSize(): string;
declare function setGeolocation(newVal: Geolocation): void;
declare function getGeolocation(): Geolocation | undefined;
declare function setOptions(newVal: IOption): void;
declare function getOptions(): IOption;
declare function setMap(newVal: Map): void;
declare function getMap(): Map;
declare function addSelectedFeature(newVal: Feature, id: number, type: string): void;
declare function removeSelectedFeature(id: number): void;
declare function removeLastSelectedFeature(): void;
declare function getSelectedFeature(id: number): Feature<Geometry> | undefined;
declare function getCurrentFeatureType(id: number): string;
declare function unselectFeatures(): void;
declare function getSelectedFeatures(): Feature<Geometry>[];
declare function setBorderConstraint(newVal: VectorLayer<Vector<Geometry>> | undefined): void;
declare function getBorderConstraint(): VectorLayer<Vector<Geometry>> | undefined;
declare function setCurrentItemId(newVal: number): void;
declare function getCurrentItemId(): number;
declare function setMaxElement(newVal: number): void;
declare function getMaxElement(): number;
export declare function useStore(): {
    setTheme: typeof setTheme;
    getTheme: typeof getTheme;
    setCustomDisplay: typeof setCustomDisplay;
    isCustomDisplay: typeof isCustomDisplay;
    setTargetBoxSize: typeof setTargetBoxSize;
    getTargetBoxSize: typeof getTargetBoxSize;
    setGeolocation: typeof setGeolocation;
    getGeolocation: typeof getGeolocation;
    setOptions: typeof setOptions;
    getOptions: typeof getOptions;
    setMap: typeof setMap;
    getMap: typeof getMap;
    addSelectedFeature: typeof addSelectedFeature;
    removeSelectedFeature: typeof removeSelectedFeature;
    removeLastSelectedFeature: typeof removeLastSelectedFeature;
    getSelectedFeature: typeof getSelectedFeature;
    getCurrentFeatureType: typeof getCurrentFeatureType;
    getSelectedFeatures: typeof getSelectedFeatures;
    unselectFeatures: typeof unselectFeatures;
    setBorderConstraint: typeof setBorderConstraint;
    getBorderConstraint: typeof getBorderConstraint;
    setCurrentItemId: typeof setCurrentItemId;
    getCurrentItemId: typeof getCurrentItemId;
    setMaxElement: typeof setMaxElement;
    getMaxElement: typeof getMaxElement;
};
export {};
