name: Geocity CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the index.js file
        run: npm run build
      
      - name: Create Tags From
        uses: jaywcjlove/create-tag-action@v1.3.14
        with:
          token: ${{ secrets.SSH_SECRET }}
          package-path: package.json